# Generated by Django 5.2.1 on 2025-05-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compras',
            field=models.ManyToManyField(blank=True, related_name='comprado_por', to='app.produto'),
        ),
        migrations.AddField(
            model_name='user',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='app.produto'),
        ),
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
