# Generated by Django 5.2.1 on 2025-05-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_compras_user_favoritos_user_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='oferta_magalu',
            field=models.BooleanField(default=False),
        ),
    ]
