# Generated by Django 5.2.1 on 2025-05-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto_oferta_magalu'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos_criados', to='app.user'),
        ),
    ]
